### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by etherbiswas** [potamides/dotfiles#2]
I would like to know how you did the wibar! I want it in my config but am too dumb to figure it out. Use 9 tags. Can you help? And i use debian btw (if that matters)

**Comment by Ahanaf-Ether** [comment]
① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ ⑩

**Comment by etherbiswas** [comment]
<pre>① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ ⑩<pre> 
or;
<pre>❶ ❷ ❸ ❹ ❺ ❻ ❼ ❽ ❾ ❿<pre>

**Comment by etherbiswas** [comment]
i found the emoji numbers!

**Comment by potamides** [comment]
Did you figure it out already? If not, to change the number of tags, you simply have to adapt this [line](https://github.com/potamides/dotfiles/blob/07c229806eba3708303fa9982bd4b976440a8c99/.config/awesome/rc.lua#L278) to your liking. The strings are used as the tag names and shown in the taglist. Hope this helps.
